accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
]

coffee_master/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from food import views as food_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^food/', include('food.urls')),
    url(r'^about/$', views.about),
    url(r'^$', food_view.homepage),
]

# override 403 error view
handler403 = 'coffee_master.views.my_custom_permission_denied_view'

food/urls.py
from django.conf.urls import url
from . import views

app_name = 'food'

urlpatterns = [
    url(r'^order/$', views.order, name="order"),
    url(r'^$', views.homepage, name="home"),
    url(r'^prepare/$', views.prepare, name="prepare"),
    url(r'^success/$', views.success, name="success"),
    url(r'^business/$', views.business, name="business"),
    url(r'^orderlist/$', views.OrderList.as_view(), name="list"),
    # pk stands for primary key; as_view() means we are using generic view
    url(r'^orderdetail/(?P<pk>[0-9]+)/$', views.OrderDetail.as_view(), name="detail"),
]

accounts/models.py
from django.db import models

# Create your models here.

food/models.py
from django.db import models

# Create your models here.
class FoodInstance(models.Model):
    class Meta:
        permissions = (
            ("can_order", "Can order the drinks"),
            ("can_serve", "Can prepare and serve the drinks"),
        )

class OrderInstance(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    coffee_order = models.CharField(max_length=100)
    done = models.BooleanField(default=False)

class BusinessObject(models.Model):
    business_status = models.CharField(max_length=10)

food/forms.py
from django import forms

COFFEE_CHOICES = [
    ('americano', 'Americano'),
    ('cappuccino', 'Cappuccino'),
    ('glace', 'Glace'),
    ('mocha', 'Mocha'),
    ('hot_chocolate', 'Hot Chocolate'),
    ('irish', 'Irish'),
    ('latte', 'Latte'),
    ('espresso', 'Espresso'),
    ('macchiato', 'Macchiato'),
]

class OrderForm(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField()
    coffee_order = forms.ChoiceField(choices=COFFEE_CHOICES, widget=forms.Select())

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.models import Permission

# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()

            #add the customer permission to newly registered user
            customer_perm = Permission.objects.get(codename='can_order')
            user.user_permissions.add(customer_perm)

            # log the user in
            login(request, user)
            return redirect('food:order')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', { 'form': form})

def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #log in the user
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('food:home')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('food:home')

coffee_master/views.py
from django.shortcuts import render

def about(request):
    return render(request, "about.html")

def my_custom_permission_denied_view(request, exception):
    return render(request, "403.html")

food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseBadRequest
from django.forms.models import model_to_dict
from django.contrib.auth.decorators import login_required, permission_required
from rest_framework import generics, permissions
from .forms import OrderForm
from .models import OrderInstance, BusinessObject
from .serializers import OrderSerializer
from .permissions import IsBaristaOnly

@login_required
@permission_required('food.can_order', raise_exception=True)
def order(request):
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            coffee_order = form.cleaned_data['coffee_order']
            # save OrderInstance to db
            customer_order = OrderInstance(name=name, email=email, coffee_order=coffee_order)
            customer_order.save()
            
            # set the pp_order (previous page order) key so user can view success page
            request.session['pp_order'] = True

            # covert model instance to dict format so it's serializable and can be used in session
            dict_order = model_to_dict(customer_order)
            request.session['order_data'] = dict_order
            return redirect('food:success')
    else:
        form = OrderForm()
    return render(request, "food/order.html", { 'form':form })

def homepage(request):
    return render(request, "food/homepage.html")

@login_required
@permission_required('food.can_serve', raise_exception=True)
def prepare(request):
    if request.method == 'POST':
        obj = BusinessObject.objects.first()
        obj.business_status = request.POST['business_status']
        obj.save()
        business_status = obj.business_status
    else:
        business_status = BusinessObject.objects.first().business_status
    orders = OrderInstance.objects.all()
    return render(request, "food/prepare.html", { 'orders':orders, 'business_status':business_status })

@login_required
def success(request):
    if 'pp_order' in request.session:
        del request.session['pp_order'] # delete the key so users won't be able to enter success page twice
        return render(request, "food/orderSuccess.html", { 'order_data': request.session['order_data'] })
    else:
        return HttpResponseBadRequest('<h1>HTTP Error 400: You need to place an order!</h1>')

def business(request):
    business_status = BusinessObject.objects.first().business_status
    return render(request, 'food/business.html', { 'business_status':business_status })

class OrderList(generics.ListCreateAPIView):
    queryset = OrderInstance.objects.all()
    serializer_class = OrderSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,)

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)

class OrderDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = OrderInstance.objects.all()
    serializer_class = OrderSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly, IsBaristaOnly,)

    def get(self, request, *args, **kwargs):
        return self.retrieve(request, *args, **kwargs)

    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Log in</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}" />
        {% endif %}
        <input type="submit" value="Login" />
    </form>
    <p>Not got an account? <a href="{% url 'accounts:signup' %}">Sign Up</a></p>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}

    <h1>signup here</h1>
        <form class="site-form" action="/accounts/signup/" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Signup">
        </form>

{% endblock %}

food/templates/food/business.html
{% extends 'base_layout.html' %}

{% block content %}

<h3>Business status now:</h3>
<div>
    <h4 id="business_status">{{ business_status }}</h4>
</div>

{% load static from staticfiles %}
<script src="{% static 'js/app.js' %}"></script>

{% endblock %}

food/templates/food/homepage.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>coffee master menu</h1>
<div>
    {% load static from staticfiles %}
    <img src="{% static 'coffee_menu.jpg' %}" alt="#" />
</div>

<a href="{% url 'food:order' %}">Ready to order?</a>

{% endblock %}

food/templates/food/order.html
{% extends 'base_layout.html' %}

{% block content %}

<div id="vue-app">
    <div class="order">
        <template v-if="businessOpen">
            <div class="alert alert-secondary" role="alert">
                    Current queue: ${queue}
            </div>
            <h1>Place your order</h1>
            <form class="site-form" action="{% url 'food:order' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form }}
                <input type="submit" value="Order">
            </form>
        </template>
        
        <template v-else-if="businessOpen===false">
            business close now
        </template>

    </div>
</div>

{% load static from staticfiles %}
<script src="{% static 'js/app.js' %}"></script>

{% endblock %}

food/templates/food/orderSuccess.html
{% extends 'base_layout.html' %}

{% block content %}

<div id="vue-app">
    <div class="order-success">
        <template v-if="orderReady">
            <div class="alert alert-success" role="alert">
                Your drink is ready to pick up!
            </div>
        </template>
        <template v-else>
            <div class="alert alert-secondary" role="alert">
                Order is in process. You are in queue: ${queue}
            </div>
        </template>
        <h4>Order summary:</h4>
        <ul>
            <li>Order ID: {{ order_data.id }}</li>
            <li>Name: {{ order_data.name }}</li>
            <li>Order: {{ order_data.coffee_order }}</li>
            <li>Your order placed at: ${orderTime}</li> 
        </ul>
        
        <br/>
        <br/>
        <p>Please don't refresh the page</p>
    </div>
</div>

{% load static from staticfiles %}
<script src="{% static 'js/app.js' %}"></script>
    
{% endblock %}

food/templates/food/prepare.html
{% extends 'base_layout.html' %}

{% block content %}

<div id="vue-app">
    <template v-if="businessOpen===''">
            Loading&#8230;
    </template>
    
    <template v-else>
        <div v-bind:class="{businessOpen: businessOpen}">
            <div id="business_status">
                <h2>Business status: {{ business_status }}</h2>
            </div>
        </div>
    </template>
    
    <div>
        <form action="{% url 'food:prepare' %}" method="post">
            {% csrf_token %}
            <button class="btn btn-success" type="submit" value="open" name="business_status">Open</button>
            <button class="btn btn-danger" type="submit" value="close" name="business_status">Close</button>
        </form>
    </div>
    
    <br/>
    <br/>

    <h3>prepare the drink</h3>
    <div class="container">
        <div class="row">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Customer Name</th>
                        <th scope="col">Order</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="order in orders" v-bind:class="{ 'order-done':order.done }">
                        <th scope="row" id="order-detail">${order.id}</th>
                        <td id="order-detail">${order.name}</td>
                        <td id="order-detail">${order.coffee_order}</td>
                        <td>
                            <button class="btn btn-info" v-on:click="getOrder(order.id)" :disabled="order.done">Edit</button>
                            <button class="btn btn-success" v-on:click="doneOrder(order.id)" :disabled="order.done">Done</button>
                            <button class="btn btn-danger" v-on:click="deleteOrder(order.id)" :disabled="!order.done">Delete</button>
                        </td>
                    </tr>
                </tbody>
            </table>


            <!-- Edit order Modal -->
            <div class="modal fade" id="editOrderModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLongTitle">EDIT ORDER</h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <form v-on:submit.prevent="updateOrder()">
                    <div class="modal-body">
                        <div class="form-group">
                          <label for="name">Customer Name</label>
                          <input
                            type="text"
                            class="form-control"
                            id="name"
                            placeholder="Enter Your Name"
                            v-model="currentOrder.name"
                            required="required" >
                        </div>
                        <div class="form-group">
                          <label for="coffee_order">Coffee Order</label>
                          <textarea
                            class="form-control"
                            id="coffee_order"
                            placeholder="Place Your Order"
                            v-model="currentOrder.coffee_order"
                            required="required"
                            rows="3"></textarea>
                        </div>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary m-progress" data-dismiss="modal">Close</button>
                      <button type="submit" class="btn btn-primary">Save changes</button>
                    </div>
                    </form>
                  </div>
                </div>
                <div class="loading" v-if="loading===true">Loading&#8230;</div>
            </div>
              <!-- End of edit order modal -->

        </div>
    </div>
    <div class="loading" v-if="loading===true">Loading&#8230;</div>
</div>

{% load static from staticfiles %}
<script src="{% static 'js/app.js' %}"></script>

{% endblock %}

templates/about.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>about page</h1>
{% endblock %}

templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- jquery 3.3.1-->
        <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>

        <!-- Bootstrap 4.1.3-->
        <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
        
        <!-- Vuejs 2.5.17-->
        <script src="{% static 'js/vue_prod.min.js' %}"></script>

        <!-- vue-resource 1.5.1 used for making web requests and handle responses-->
        <script src="{% static 'js/vue-resource.min.js' %}"></script>
        
        <!-- custom style -->
        <link rel="stylesheet" href="{% static 'styles.css' %}">

        <title>Coffee Master</title>

        <!-- Favicon -->
        <link rel="apple-touch-icon" sizes="120x120" href="{% static 'favicon/apple-touch-icon.png' %}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
        <link rel="manifest" href="{% static 'favicon/site.webmanifest' %}">
        <link rel="mask-icon" href="{% static 'favicon/safari-pinned-tab.svg' %}" color="#5bbad5">
        <meta name="msapplication-TileColor" content="#da532c">
        <meta name="theme-color" content="#ffffff">

        
    </head>
    <body>
        <header class="wrapper">
            <h1><a href="{% url 'food:home' %}"><img src="{% static 'logo.jpg' %}" alt="#" /></a></h1>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                    <li>Hi, {{ request.user.username }}</li>
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>

                    {% if perms.food.can_order %}
                    <li><a href="{% url 'food:order' %}" class="highlight">Order Drinks</a></li>
                    {% endif %}

                    {% if perms.food.can_serve %}
                    <li><a href="{% url 'food:prepare' %}" class="highlight">Manage Orders</a></li>
                    {% endif %}

                    {% else %}
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>